///py_clear_exception()
// Clear current exception
global._PY_EXCEPTION = false; 
