///py_check_exception()
// Check if we have an exception to catch 
return global._PY_EXCEPTION == true;
